import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/components/Nav&fot/navbar";
import { Footer } from "@/components/Nav&fot/footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
